### ISSUE TITLE
Project name missing

### ISSUE THREAD

**Issue by maierfelix** [maierfelix/PokeMMO#10]
The engine/project needs a unique super-blazing-cool name, please suggest below!

**Comment by Ehesp** [comment]
PokémmoEngine :see_no_evil:

**Comment by Salakar** [comment]
@Ehesp PokémmonEngine 👌  haha

**Comment by lubien** [comment]
Since you're basing your project in Pokemon, to prevent any copyright problems, you could use a reference name like:
- Pocket Engine
- Monster Engine
- Trainer Engine

Forgive my low creativity, but you got the idea e.e

**Comment by silurt** [comment]
@lubien omg pocket engine genuus

**Comment by Myaats** [comment]
I agree on Pocket Engine, it fits, does not sound bad and has no direct connection to the Pokemon brand.

**Comment by maierfelix** [comment]
+1 Pocket Engine

**Comment by Tzogi** [comment]
How about... PockÉngine?

**Comment by tzogi** [comment]
Pokéngine

**Comment by maierfelix** [comment]
@Tzogi sadly this name is already taken by another pokemon fangame.

**Comment by lubien** [comment]
I'm glad you liked pocket engine :D

**Comment by wtw0987** [comment]
Pocket Engine FTW!

**Comment by BarrendG** [comment]
Pocket Engine seems quite good ,yep

**Comment by maierfelix** [comment]
Pocket Engine will be used, thanks everyone!
