### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by Salakar** [maierfelix/PokeMMO#3]
Have you considered maybe packaging this in electron as an app?

You could focus entirely on chrome only support then as that's basically what electron is plus you get an additional main process - so the web view could purely be for handling visuals and the node backend could handle any long running/intensive logic via synchronous and asynchronous message events ([ipcRenderer](http://electron.atom.io/docs/v0.37.7/api/ipc-renderer/))

Could also then potentially package this as an actual cross platform app 

Thoughts 💭  ?

**Comment by maierfelix** [comment]
The idea is good, but sadly the project isn't in such a ready state yet.

Anyway I think deploying the editor by electron would be awesome! You can download the binaries from the (_currently missing_) website, run the editor, create a map, click save, choose export (all platforms|specific platform) - and your ready to use production build gets outputted.

Thanks for the kind idea!

**Comment by shockwavemoto** [comment]
Have you considered maybe packaging this in electron as an app?

You could focus entirely on chrome only support then as that's basically what electron is plus you get an additional main process - so the web view could purely be for handling visuals and the node backend could handle any long running/intensive logic via synchronous and asynchronous message events (ipcRenderer)

Could also then potentially package this as an actual cross platform app

true that and could not agree more but electron requires jsx which is quite hard to write and build so don;t think as to be a good idea
