### ISSUE TITLE
Buildings are missing 

### ISSUE THREAD

**Issue by markolo25** [maierfelix/PokeMMO#9]
I  tried this before, and I get this now.

![screen shot 2016-04-28 at 5 32 55 pm](https://cloud.githubusercontent.com/assets/1953943/14905630/526f14c8-0d67-11e6-9c50-fe9c2edbda14.png)

**Comment by maierfelix** [comment]
This is a water area, placed below the background tile map.
I had to replace some graphics - will get fixed in the next few commits, thank you.
